exclude: 'docs|test|setup.py'
repos:  
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks: 
      - id: flake8
        language_version: python

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        language_version: python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        language_version: python