[tox]
envlist = py311,py312,py313,py314

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
extras = test,distributed
commands = python -m pytest

[testenv:build]
skip_install = true
deps = build
commands = python -m build

[testenv:release]
skip_install = true
deps =
    build
    twine
setenv =
    TWINE_USERNAME = {env:TWINE_USERNAME}
    TWINE_PASSWORD = {env:TWINE_PASSWORD}
commands =
    {[testenv:build]commands}
    twine upload --skip-existing dist/*
